Tweets = new (Mongo.Collection)('tweets')
if Meteor.isServer

  getTweets = (username, count, callback) ->
    Tweets.remove {}
    T = new Twit(
      consumer_key: 'CbqeFfqUzsE9JgmmLTjAebyt7'
      consumer_secret: '5Q6XpRSj261SMEaNhekzlviIIj1nNcNd3A2vgpEeLXrXT3GbK5'
      access_token: '3256361616-o13asDcdneszFfT35PRgHy0pxVtHYPRgmFmc007'
      access_token_secret: 'fqqB9nArN9dlANpiS1GwtMTfrFcMiCmaRvdeODe1kowqX')
    # T.get('search/tweets', {
    #         q: "plebs",
    #         count: 10,
    #     },
    #     function(err, data) {
    #         callback(err, data);
    #     }
    # );
    T.get 'statuses/user_timeline', {
      screen_name: username
      count: count
    }, (err, data) ->
      callback err, data
      return
    return

  storeTweets = (response) ->
    # var array = response.statuses;
    array = response
    i = 0
    while i < array.length
      Tweets.insert
        message: array[i].text
        time: array[i].created_at
      i++
    return

  # Meteor.publish("tweets", function() {
  #     return Tweets.find();
  # });
  Meteor.methods grabResults: (twittername, count) ->
    twe = Meteor.wrapAsync(getTweets)
    try
      tweeters = twe(twittername, count)
      storeTweets tweeters
    catch error
      console.log 'Could not find request.'
    false
if Meteor.isClient
  # Meteor.subscribe("tweets");
  Template.tweetSubmit.events 'submit form': (e, template) ->
    e.preventDefault()
    $target = $(e.target)
    username = $target.find('[name=twitterName]').val()
    count = $target.find('[name=count]').val()
    if username != '' and count != ''
      Meteor.call 'grabResults', username, count, (err) ->
        if err
          console.log err
        return
    else
      console.log 'forms are not filled'
    template.find('form').reset()
    return
  Template.twitterPackage.helpers tweets: ->
    Tweets.find()

# ---
# generated by js2coffee 2.0.4